[package]
name = "roead"
description = "Rust bindings for oead C++ library for common Nintendo formats"
version = "0.1.0"
authors = ["Caleb Smith <email@calebdixonsmith.top>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/NiceneNerd/roead"
documentation = "https://docs.rs/roead"
keywords = ["Nintendo", "aamp", "byml", "sarc", "Zelda", "gamedev"]
categories = ["game-development", "parsing"]
edition = "2018"

[dependencies]
cached = "0.25.0"
cxx = "1.0.49"
crc = "2.0.0"
derivative = "2.1.1"
indexmap = "1.6.2"
lazy_static = "1.4.0"
thiserror = "1.0.22"
unicase = "2.6.0"

[dev-dependencies]
glob = "*"
rayon = "1.5.0"

[build-dependencies]
cxx-build = "1.0.49"
glob = "*"
