[package]
name = "roead"
description = "Rust bindings for oead C++ library for common Nintendo formats"
version = "0.10.2"
authors = ["Caleb Smith <email@calebdixonsmith.top>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/NiceneNerd/roead"
documentation = "https://nicenenerd.github.io/roead/roead"
keywords = ["Nintendo", "aamp", "byml", "sarc", "gamedev"]
categories = ["game-development", "parsing"]
edition = "2021"
exclude = ["/include/oead/test"]

[features]
with-serde = ["serde", "indexmap/serde"]

[dependencies]
cached = "0.26.2"
cxx = "1.0.68"
crc = "2.0.0"
derivative = "2.1.1"
indexmap = "1.6.2"
lazy_static = "1.4.0"
serde = { version = "1.0.136", features = ["derive"], optional = true }
thiserror = "1.0.22"
unicase = "2.6.0"

[dev-dependencies]
glob = "0.3.0"
rayon = "1.5.0"

[build-dependencies]
cxx-build = "1.0.49"
glob = "0.3.0"
