[package]
name = "roead"
version = "0.1.0"
authors = ["Caleb Smith <macadamiadaze@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.25"
derivative = "2.1.1"
thiserror = "1.0.22"

[build-dependencies]
cxx-build = "1.0.25"
glob = "*"