[package]
name = "roead"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
ahash = { version = "0.7.6", optional = true}
binrw = { version = "0.9.2", optional = true }
cached = "0.36.0"
cxx = "1.0.71"
decorum = { version = "0.3.1", optional = true }
enum-as-inner = { version = "0.5.0", optional = true } 
join_str = "0.1.0"
num-integer = { version = "0.1.45", optional = true }
rustc-hash = "1.1.0"
serde = { version = "1.0.139", features = ["derive"], optional = true }
serde_json = { version = "1.0.82", optional = true }
smartstring = "1.0.1"
static_assertions = "1.1.0"
thiserror = "1.0.31"

[build-dependencies]
cxx-build = "1.0.71"

[dev-dependencies]
# roead = "0.12.2"

[features]
aamp = ["decorum", "enum-as-inner"]
byml = ["binrw", "decorum", "enum-as-inner"]
sarc = ["binrw", "num-integer", "serde", "serde_json"]
yaz0 = []
with-serde = ["serde", "decorum/serde", "smartstring/serde"]
default = ["aamp", "byml", "sarc", "yaz0"]
