[package]
name = "roead"
version = "0.1.0"
authors = ["Caleb Smith <macadamiadaze@gmail.com>"]
edition = "2018"

#[lib]
#crate_type = ["staticlib"]

[dependencies]
cxx = "1.0.49"
derivative = "2.1.1"
thiserror = "1.0.22"

[build-dependencies]
cxx-build = "1.0.49"
glob = "*"
