name: release

on:
  release:
    types:
      - created

jobs:
  release-win:
    runs-on: [windows-latest]
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init --recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip setuptools wheel
    - name: Build
      run: python setup.py bdist_wheel
    - name: Upload wheels
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install --upgrade twine
        twine upload dist/*.whl

  release-lin:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init --recursive
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Build
      uses: RalfG/python-wheels-manylinux-build@v0.2-manylinux2014_x86_64
      with:
        python-versions: 'cp36-cp36m cp38-cp38'
        system-packages: 'epel-release cmake3'
        package-path: ''
    - name: Upload wheels
      uses: actions/upload-artifact@master
      with:
        name: wheelhouse
        path: wheelhouse
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade twine
        twine upload wheelhouse/*-manylinux*.whl

  release-lin-with-docs:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init --recursive
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Build
      uses: RalfG/python-wheels-manylinux-build@v0.2-manylinux2014_x86_64
      with:
        python-versions: 'cp37-cp37m'
        system-packages: 'epel-release cmake3'
        package-path: ''
    - name: Upload wheels
      uses: actions/upload-artifact@master
      with:
        name: wheelhouse
        path: wheelhouse
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade twine
        twine upload wheelhouse/*-manylinux*.whl
    - name: Trigger documentation build
      run: curl -X POST -d "branches=latest" -d "token=${{ secrets.RTD_TOKEN }}" https://readthedocs.org/api/v2/webhook/oead/112051/
